### PR TITLE
Added English translation files and corrected some minor terminology issues.

### PR DESCRIPTION
**Pull request by toddcarnes**
There were a couple of things I wasn't sure of. If I wasn't sure what you meant. I left it the way you had it and left a comment in the ts file.

### CODE REVIEW

**Comment by atten** [comment]
Thanks a lot!
I've made corrections according to your advices.
I've define planet that rises right behind the Sun as "Auriga", and planet that rises before the Sun as "Doryphoros". Is that correct?

**Comment by toddcarnes** [comment]
On 03/28/2014 07:11 PM, Artem wrote:

> Thanks a lot!
> I've made corrections according to your advices.
> I've define planet that rises right behind the Sun as "Auriga"
> 
> This is "Occidental"
> 
> , and planet that rises before the Sun as "Doryphoros".

This is "Oriental".

I didn't know what you meant with these, so I didn't change them in the 
ts file. Do you want to change it, or do you want me to change it and 
send another pull request?

Todd

**Comment by toddcarnes** [comment]
Oh wait on that... I just realized you are talky about the doryphory. 
Wait on this. I need to check something out. The doryphory is are used 
in Hellenistic astrology. I practice Western Traditional, but I have a 
couple friends that practise Hellenistic Astrology. Let me check with 
them and get back to you.

Todd

**Comment by atten** [comment]
"Doryphoros" and "Auriga" are in Astroprocessor ZET (http://zaytsev.com/index.html):

**Comment by toddcarnes** [comment]
I know, but I wanted to make sure I had the definition right, before I 
told you...

The doryphory, or spear-bearers, are the planets that are in the same 
sign as the Sun (or Moon).

In the case of the Sun, they have to be oriental (rise before) to the 
Sun. In the case of the Moon, they have to be occidental (rise after) of 
the Moon. In the example you included it looks like the Moon is 
doryphory for both the Sun AND the Moon. Also, I think (but I'm not 
sure), the Moon probably should have been counted as doryphory for the 
Sun as well, but I'm not sure why it isn't in this picture.

I had forgotten about them, because I never use them.

I still don't know what Auriga means. Have you tried contacting the 
people that make Zet? (I always liked Zet, but haven't used it since 
version 7.)

Todd

**Comment by toddcarnes** [comment]
Sorry, I'm tired and need to go to bed. That should have read... "In the 
example you included, it looks like _Mercury_ is doryphory for both the 
Sun AND the Moon."

Todd

**Pull request merged**
